### ISSUE TITLE
Display project tags

### ISSUE THREAD

**Issue by PhilomathMac** [arifszn/gitprofile#147]
I would love to be able to display my project tags on my portfolio website. According to [GitHub Docs](https://docs.github.com/en/rest/repos/repos#list-repository-tags), we can get a list of each repo's tags using this query: 

```
https://api.github.com/repos/\(OWNER)/\(REPO)/tags
```

Perhaps we could reuse the code used to create the skill bubbles to create tag bubbles.

I'm not sure where we can store a list of the repo's tags in order to reference them later when building the project html. I have very limited experience working with web development, so I'm not exactly sure where to start.

**Comment by arifszn** [comment]
Nice feature idea. But the problem is, that we can only use the Github API for a limited time as the requests are not authenticated. So using that API for every repo would affect our [rate limits](https://docs.github.com/en/rest/overview/resources-in-the-rest-api) and users would see this page often.
![image](https://user-images.githubusercontent.com/45073703/186927053-3f8860b1-e688-47de-a207-6c6e3640e98e.png)

Also, the data related GitHub's content is real-time and we are not storing them anywhere. Meaning if you change your profile picture on GitHub, GitProfile would show the new picture without rebuilding.
