### ISSUE TITLE
Remove strict `endOfLine` style rule

### ISSUE THREAD

**Issue by arifszn** [arifszn/gitprofile#198]
https://github.com/arifszn/gitprofile/pull/196#issuecomment-1278954711

**Comment by jsvigneshkanna** [comment]
Would like to take this issue

**Comment by arifszn** [comment]
As hacktoberfest is closing soon, @knittl you can work on this if @jsvigneshkanna is not available.

**Comment by knittl** [comment]
Yes, I can do it. How exactly would I verify correct eslint config and behavior?

In other words: what is the expected behavior after this change? Being able to write an array with short values as multi-line array? Somehow that still doesn't work. Or handle CRLF/LF issues? I don't think we would want CRLF in the committed sources, only LF.

**Comment by arifszn** [comment]
handle CRLF/LF issues. I mean we should ignore the checking. 

> I don't think we would want CRLF in the committed sources, only LF.

In Windows machines, the prettier often throws errors for the `endOfLine` rule. To make the contribution user-friendly, we should accept LF and CRLF both. Thoughts?

**Comment by knittl** [comment]
But wouldn't we want to prevent CRLF making it into the commits? I'm fine either way, but PR action workflows need a separate check then to prevent inconsistent line breaks?
