### ISSUE TITLE
Add option to display footer specified by user

### ISSUE THREAD

**Issue by arifszn** [arifszn/gitprofile#207]
Add an option in the `gitprofile.config.js` titled **`footer`**.

```js
const config = {
  // ..............
  footer: 'Custom footer'
};
```

Use this new config in `src/components/GitProfile.jsx` to display the footer.

Please follow the checklist:

- [ ] The footer should be optional
- [ ] Update Readme
- [ ] Update prop definition
- [ ] Update type definition in `types/index.d.ts`

**Comment by RachitGarg-12** [comment]
@arifszn  i would like to contribute to this issue.

**Comment by arifszn** [comment]
@RachitGarg-12 any update?

**Comment by csarnataro** [comment]
Hi, I can have a look at this issue, if @RachitGarg-12 is ok with it.

I have one question about the functionality to implement.

Do you think it's ok to have a simple text-only footer (like the one in the example above, `footer: 'Custom footer'`) or we should support markdown as well? So that we can add links in the footer and mix text and footer.

Moreover, if we go with the text-only solution, should we wrap the footer in a link? Like the current footer?
In that case, I think we should add another configuration like:
```js
footer: 'Custom footer'
footerLink: 'https://github.com/username/`
```
Thoughts?

**Comment by arifszn** [comment]
It should accept HTML. So that user can have more control over what to display. Something like:
```jsx
<React.Fragment>
  <a
    className="card-body"
    href="https://github.com/arifszn/gitprofile"
    target="_blank"
    rel="noreferrer"
  >
    <div>
      {loading ? (
        skeleton({ width: 'w-52', height: 'h-6' })
      ) : (
        <p className="font-mono text-sm">
          Made with <span className="text-primary">GitProfile</span> and ❤️
        </p>
      )}
    </div>
  </a>
</React.Fragment>;

```

**Comment by csarnataro** [comment]
Do you mean also JSX would be acceptable? I mean, also with `{loading ? (..)}` and JavaScript expressions?
To be honest, it seems a little bit "overkill" for me.

I think that probably regular HTML would give users enough power to add and format whatever they want. Like:

```js
const config = {
  // ..............
  footer: `<a href="https://www.example.com" class="card-body" target="_blank" rel="noreferrer">
                  <p class="font-mono text-sm">
                    Custom footer added by <span class="text-primary">me</span> in <strong>2023</strong>
                  </p>                   
               </a>`
};
```
Please notice use of `class` instead of `className`, 

I did a quick experiment parsing a HTML text with `html-react-parser` (https://www.npmjs.com/package/html-react-parser) and I came up with this:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/11388820/210607807-3c741a48-e730-47d2-bcc0-846bf5a27e6b.png">

What do you think? If HTML is enough, I have a PR almost ready.

**Comment by arifszn** [comment]
Ignore the loading and jsx. But the loading skeleton should be handled too from the app side.

Do we need a library for it? How about using `dangerouslySetInnerHTML`? Any downside?

**Comment by csarnataro** [comment]
In general I don't love `dangerouslySetInnerHTML` but in this case I think it's safe using it, as long as the content of the footer is coming from the user.

**Comment by csarnataro** [comment]
This is what I achieved with `dangerouslySetInnerHTML`

<img width="455" alt="image" src="https://user-images.githubusercontent.com/11388820/210631377-e1fdaf6d-73a7-4585-a579-d0246d4d89f2.png">

The loading skeleton looks like this:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/11388820/210631471-29192368-5e16-4eee-b292-70ee336c434b.png">

I'm opening a PR in a few minutes.
