### ISSUE TITLE
Images not loading/not detected

### ISSUE THREAD

**Issue by jonas4climate** [arifszn/gitprofile#608]
I forked the current repo and set it up, so far amazing! But when trying to use the imageURL images, nothing is working, it's either not detected or gets the loading animation for the image.

Portfolio link: https://jonas4climate.github.io/
Image links are in my [config file](https://github.com/jonas4climate/jonas4climate.github.io/blob/main/gitprofile.config.ts) and I also tried a "local" version by using links such as these https://github.com/jonas4climate/jonas4climate.github.io/tree/main/files to point to a files folder in that repo.

Would appreciate any help what causes the problem here!

**Comment by arifszn** [comment]
Thanks for trying out the project.

The issue with the image URL is that, you are using a Google Drive link instead of an image URL.
The correct image URL should be https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYKK4KzRM5W2bqK1P_4cE9VWIy4PC5wh70s06WTDl_mprt6olBACxF2MlG3ICT9qVgIXRUBqZo5xZGLsK_wJszAbV50lZBb9j8=w1920-h951-rw-v1.

And if you want to use the local images, the image URL should be like this: https://raw.githubusercontent.com/jonas4climate/jonas4climate.github.io/main/files/youth_talk.jpg.

**Comment by jonas4climate** [comment]
Thank you so much for the explanation, much appreciated, that fixed it. Really think your layout is the simplest and cleanest from all templates I could find.
